# =============================================================================
# Perfil: Database — Servidor dedicado de base de datos
# =============================================================================
# Linux System Optimizer (LSO)
# Autor: Ricardo Rosero <rrosero2000@gmail.com>
# GitHub: https://github.com/rr-n4p5t3r
# Licencia: GPLv3
# =============================================================================

LSO_PROFILE_NAME="database"
LSO_OPTIMIZE_SERVICES=true
LSO_CLEAN_CACHE=true
LSO_ZRAM_ENABLED=false
LSO_DB_START_DATABASES=true
LSO_DB_SWAPPINESS=1
LSO_DB_DIRTY_RATIO=10
LSO_DB_DIRTY_BACKGROUND_RATIO=5
