# =============================================================================
# Perfil: Desktop — Uso general de escritorio
# =============================================================================
# Linux System Optimizer (LSO)
# Autor: Ricardo Rosero <rrosero2000@gmail.com>
# GitHub: https://github.com/rr-n4p5t3r
# Licencia: MIT
# =============================================================================

LSO_PROFILE_NAME="desktop"
LSO_OPTIMIZE_DESKTOP=true
LSO_OPTIMIZE_BROWSER=true
LSO_OPTIMIZE_SERVICES=true
LSO_CLEAN_CACHE=true
LSO_ZRAM_ENABLED=false
LSO_SWAPPINESS=10
