# =============================================================================
# Perfil: Dev — Estación de desarrollo (bases de datos, entornos, lenguajes)
# =============================================================================
# Linux System Optimizer (LSO)
# Autor: Ricardo Rosero <rrosero2000@gmail.com>
# GitHub: https://github.com/rr-n4p5t3r
# Licencia: MIT
# =============================================================================

LSO_PROFILE_NAME="dev"
LSO_OPTIMIZE_SERVICES=true
LSO_CLEAN_CACHE=true
LSO_ZRAM_ENABLED=false
LSO_SWAPPINESS=10
LSO_DEV_START_DATABASES=true
LSO_DEV_INCREASE_INOTIFY=true
LSO_DEV_INOTIFY_WATCHES=524288
