# =============================================================================
# Perfil: Gaming — Máximo rendimiento para juegos
# =============================================================================
# Linux System Optimizer (LSO)
# Autor: Ricardo Rosero <rrosero2000@gmail.com>
# GitHub: https://github.com/rr-n4p5t3r
# Licencia: GPLv3
# =============================================================================

LSO_PROFILE_NAME="gaming"
LSO_OPTIMIZE_DESKTOP=true
LSO_OPTIMIZE_BROWSER=false
LSO_OPTIMIZE_SERVICES=true
LSO_CLEAN_CACHE=false
LSO_ZRAM_ENABLED=false
LSO_SWAPPINESS=1
LSO_CPU_GOVERNOR="performance"
LSO_DISABLE_COMPOSITOR=true
