# =============================================================================
# blacklist.conf — Procesos candidatos para optimización/terminación
# =============================================================================
# Linux System Optimizer (LSO)
# Autor: Ricardo Rosero <rrosero2000@gmail.com>
# GitHub: https://github.com/rr-n4p5t3r
# Licencia: MIT
# =============================================================================

tracker-miner
tracker-miner-fs
tracker-store
tracker-extract
baloo_file
baloo_file_extractor
zeitgeist-daemon
zeitgeist-datahub
mission-control-5
evolution-addressbook-factory
evolution-calendar-factory
evolution-source-registry
packagekitd
snapd
snapd.socket
flatpak-system-helper
appimagelauncherd
spice-vdagent
gnome-software
plasma-discover
