# =============================================================================
# whitelist.conf — Procesos y servicios críticos que NUNCA deben modificarse
# =============================================================================
# Linux System Optimizer (LSO)
# Autor: Ricardo Rosero <rrosero2000@gmail.com>
# GitHub: https://github.com/rr-n4p5t3r
# Licencia: MIT
# =============================================================================

systemd
init
kthreadd
kernel
bash
zsh
login
sshd
Xorg
Xwayland
gnome-shell
plasmashell
cinnamon
xfce4-session
mate-session
lxqt-session
budgie-panel
cosmic-session
dbus-daemon
NetworkManager
pipewire
pipewire-pulse
pulseaudio
gdm
sddm
lightdm
loginwindow
udevd
systemd-journald
systemd-logind
